# These are supported funding model platforms

github: [anshulmttl]
patreon: [anshulmttl]
open_collective: [anshulmttl]
ko_fi: [anshulmttl]
tidelift: WebFilter/WebFilter
community_bridge: WebFilter
liberapay: [anshulmttl]
issuehunt: [anshulmttl]
lfx_crowdfunding: WebFilter
polar: [anshulmttl]
buy_me_a_coffee: [anshulmttl]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
